In [138]:
import numpy as np

from FEM_1D_Functions import *

# configure solver inputs
a = 0
b = 1
L = 1.0
u_a = 0
u_b = 1.0
alpha = 5.0

domain = [a, b]
degree = 2
size = .1

generateMeshNodes(a_Domain, a_Degree, a_Size)
print("Number of Elements:", numElements)
print("Number of Nodes:", numNodes)
print("List of Nodes:", nodes)

generateMeshConnectivity(numElements, degree)

print("Connectivity Matrix:", connectivity)

Number of Elements: 10
Number of Nodes: 21
List of Nodes: [0.   0.05 0.1  0.15 0.2  0.25 0.3  0.35 0.4  0.45 0.5  0.55 0.6  0.65
 0.7  0.75 0.8  0.85 0.9  0.95 1.  ]
Connectivity Matrix: [[ 0  1  2]
 [ 2  3  4]
 [ 4  5  6]
 [ 6  7  8]
 [ 8  9 10]
 [10 11 12]
 [12 13 14]
 [14 15 16]
 [16 17 18]
 [18 19 20]]
